name: SAP Adaptive Server Enterprise

on:
 push:
  paths:
    - 'sap-ase/**'
    - 'test/**'
    - '.github/workflows/sap-ase_server.yaml'
  pull_request:
    paths:
    - 'sap-ase/**'
    - 'test/**'
    - '.github/workflows/sap-ase_server.yaml'

env:
  REPOSITORY: "docker.io/sqlops/sybase"
  DOCKERFILE: "ansible-ase/Dockerfile.ci"
  ENF_FILE: "./ansible-ase/.env"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: FranzDiebold/github-env-vars-action@v1.2.1
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Set ENV variables
        run: |
          cat ${{ env.ENV_FILE }} >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Build image
        run: |
          docker image build -f ${{ env.DOCKERFILE }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_MAJOR }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_MINOR }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_PATCH }} \
          --tag ${{ env.REPOSITORY}}:${{ env.SEMVER_TAG }} \
          --tag ${{ env.REPOSITORY}}:latest \
          ./

      - name: Test Shell
        run: |
          ls -lha
          docker run -d --name sybase \
          -v "$(pwd)/test/dataset:/var/lib/dataset" \
          -p 5000:5000 \
          docker.io/sqlops/sybase:${{ env.SEMVER_TAG }}
          chmod +x ./test/docker_image.sh
          ./test/docker_image.sh
          sleep 10
          ./test/docker_image.sh

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: Test Python
        run: |
          chmod +x ./test/import_fakenames.sh
          ./test/import_fakenames.sh

      - name: Push image
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPOSITORY}}
          context: ./
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: True
